spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin279.
    url: jdbc:mysql://mysql.pspo.com/short_url
    # 配置 DataSource Driver  使用SHARDINGSPHERE-JDBC
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
  #    redis
  redis:
    host: service.pspo.com
logging:
  level:
    com.fasturl.shorturlservice.mapper: debug